name: Deploy to Fly
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Run deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            persist-credentials: false

      - name: Setup environment
        uses: ./.github/setup

      - name: Run migrations
        run: pnpm --filter=api run db:generate && pnpm --filter=api run db:migrate
        continue-on-error: true
        env:
            TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
            TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}

      - name: Deploy to Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --dockerfile apps/api/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}