name: Deploy backend
on:
  push:
    branches:
      - main
jobs:
  migrations:
    name: Run migrations
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            persist-credentials: false

      - name: Setup environment
        uses: ./.github/setup

      - name: Run migrations
        run: pnpm --filter=api run db:generate && pnpm --filter=api run db:migrate
        env:
            TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
            TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
  deploy:
    name: Deploy backend
    runs-on: ubuntu-latest
    concurrency: deploy-group
    needs: migrations
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            persist-credentials: false
            
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}